# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.

obj-y	+= crc16_test.o
obj-y	+= gpio.o
obj-y	+= spi_nand_flash.o
obj-y	+= copy_image.o
obj-y	+= ucp_init.o



