//******************** (C) COPYRIGHT 2019 SmartLogic*******************************
// FileName           : dw_ahb_ictl.h
// Author             : lijian, jian.li@smartlogictech.com
// Date First Issued  : 2019-03-29 02:46:53 PM
// Last Modified      : 2019-03-29 04:08:27 PM
// Description        :
// ------------------------------------------------------------
// Modification History:
// Version    Date       Author    Modification Description
//
//**********************************************************************************
#ifndef __ICTL_H__
#define __ICTL_H__

#define DW_AHB_ICTL0_BASE         0x049bc000
#define DW_AHB_ICTL1_BASE         0x049bd000
#define DW_AHB_ICTL2_BASE         0x049be000

#define IRQ_INTEN_OFFSET          0x000
#define IRQ_INTEN_OFFSET_L        0x000
#define IRQ_INTEN_OFFSET_H        0x004
#define IRQ_INTMASK_OFFSET        0x008
#define IRQ_INTMASK_OFFSET_L      0x008
#define IRQ_INTMASK_OFFSET_H      0x00c
#define IRQ_INTFORCE_OFFSET       0x010
#define IRQ_INTFORCE_OFFSET_L     0x010
#define IRQ_INTFORCE_OFFSET_H     0x014
#define IRQ_RAWSTATUS_OFFSET      0x018
#define IRQ_RAWSTATUS_OFFSET_L    0x018
#define IRQ_RAWSTATUS_OFFSET_H    0x01c
#define IRQ_STATUS_OFFSET         0x020
#define IRQ_STATUS_OFFSET_L       0x020
#define IRQ_STATUS_OFFSET_H       0x024
#define IRQ_MASKSTATUS_OFFSET     0x028
#define IRQ_MASKSTATUS_OFFSET_L   0x028
#define IRQ_MASKSTATUS_OFFSET_H   0x02c
#define IRQ_FINALSTATUS_OFFSET    0x030
#define IRQ_FINALSTATUS_OFFSET_L  0x030
#define IRQ_FINALSTATUS_OFFSET_H  0x034
#define IRQ_VECTOR_OFFSET         0x038
#define IRQ_VECTOR_OFFSET_L       0x038
#define IRQ_VECTOR_OFFSET_H       0x03c
#define IRQ_VECTOR_OFFSET_0       0x040
#define IRQ_VECTOR_OFFSET_0_L     0x040
#define IRQ_VECTOR_OFFSET_0_H     0x044
#define IRQ_VECTOR_OFFSET_1       0x048
#define IRQ_VECTOR_OFFSET_1_L     0x048
#define IRQ_VECTOR_OFFSET_1_H     0x04c
#define IRQ_VECTOR_OFFSET_2       0x050
#define IRQ_VECTOR_OFFSET_2_L     0x050
#define IRQ_VECTOR_OFFSET_2_H     0x054
#define IRQ_VECTOR_OFFSET_3       0x058
#define IRQ_VECTOR_OFFSET_3_L     0x058
#define IRQ_VECTOR_OFFSET_3_H     0x05c
#define IRQ_VECTOR_OFFSET_4       0x060
#define IRQ_VECTOR_OFFSET_4_L     0x060
#define IRQ_VECTOR_OFFSET_4_H     0x064
#define IRQ_VECTOR_OFFSET_5       0x068
#define IRQ_VECTOR_OFFSET_5_L     0x068
#define IRQ_VECTOR_OFFSET_5_H     0x06c
#define IRQ_VECTOR_OFFSET_6       0x070
#define IRQ_VECTOR_OFFSET_6_L     0x070
#define IRQ_VECTOR_OFFSET_6_H     0x074
#define IRQ_VECTOR_OFFSET_7       0x078
#define IRQ_VECTOR_OFFSET_7_L     0x078
#define IRQ_VECTOR_OFFSET_7_H     0x07c
#define IRQ_VECTOR_OFFSET_8       0x080
#define IRQ_VECTOR_OFFSET_8_L     0x080
#define IRQ_VECTOR_OFFSET_8_H     0x084
#define IRQ_VECTOR_OFFSET_9       0x088
#define IRQ_VECTOR_OFFSET_9_L     0x088
#define IRQ_VECTOR_OFFSET_9_H     0x08c
#define IRQ_VECTOR_OFFSET_10      0x090
#define IRQ_VECTOR_OFFSET_10_L    0x090
#define IRQ_VECTOR_OFFSET_10_H    0x094
#define IRQ_VECTOR_OFFSET_11      0x098
#define IRQ_VECTOR_OFFSET_11_L    0x098
#define IRQ_VECTOR_OFFSET_11_H    0x09c
#define IRQ_VECTOR_OFFSET_12      0x0a0
#define IRQ_VECTOR_OFFSET_12_L    0x0a0
#define IRQ_VECTOR_OFFSET_12_H    0x0a4
#define IRQ_VECTOR_OFFSET_13      0x0a8
#define IRQ_VECTOR_OFFSET_13_L    0x0a8
#define IRQ_VECTOR_OFFSET_13_H    0x0ac
#define IRQ_VECTOR_OFFSET_14      0x0b0
#define IRQ_VECTOR_OFFSET_14_L    0x0b0
#define IRQ_VECTOR_OFFSET_14_H    0x0b4
#define IRQ_VECTOR_OFFSET_15      0x0b8
#define IRQ_VECTOR_OFFSET_15_L    0x0b8
#define IRQ_VECTOR_OFFSET_15_H    0x0bc
#define FIQ_INTEN_OFFSET          0x0c0
#define FIQ_INTMASK_OFFSET        0x0c4
#define FIQ_INTFORCE_OFFSET       0x0c8
#define FIQ_RAWSTATUS_OFFSET      0x0cc
#define FIQ_STATUS_OFFSET         0x0d0
#define FIQ_FINALSTATUS_OFFSET    0x0d4
#define IRQ_PLEVEL_OFFSET         0x0d8
#define IRQ_P0_OFFSET             0x0e8
#define IRQ_P1_OFFSET             0x0ec
#define IRQ_P2_OFFSET             0x0f0
#define IRQ_P3_OFFSET             0x0f4
#define IRQ_P4_OFFSET             0x0f8
#define IRQ_P5_OFFSET             0x0fc
#define IRQ_P6_OFFSET             0x100
#define IRQ_P7_OFFSET             0x104
#define IRQ_P8_OFFSET             0x108
#define IRQ_P9_OFFSET             0x10c
#define IRQ_P10_OFFSET            0x110
#define IRQ_P11_OFFSET            0x114
#define IRQ_P12_OFFSET            0x118
#define IRQ_P13_OFFSET            0x11c
#define IRQ_P14_OFFSET            0x120
#define IRQ_P15_OFFSET            0x124
#define IRQ_P16_OFFSET            0x128
#define IRQ_P17_OFFSET            0x12c
#define IRQ_P18_OFFSET            0x130
#define IRQ_P19_OFFSET            0x134
#define IRQ_P20_OFFSET            0x138
#define IRQ_P21_OFFSET            0x13c
#define IRQ_P22_OFFSET            0x140
#define IRQ_P23_OFFSET            0x144
#define IRQ_P24_OFFSET            0x148
#define IRQ_P25_OFFSET            0x14c
#define IRQ_P26_OFFSET            0x150
#define IRQ_P27_OFFSET            0x154
#define IRQ_P28_OFFSET            0x158
#define IRQ_P29_OFFSET            0x15c
#define IRQ_P30_OFFSET            0x160
#define IRQ_P31_OFFSET            0x164
#define IRQ_P32_OFFSET            0x168
#define IRQ_P33_OFFSET            0x16c
#define IRQ_P34_OFFSET            0x170
#define IRQ_P35_OFFSET            0x174
#define IRQ_P36_OFFSET            0x178
#define IRQ_P37_OFFSET            0x17c
#define IRQ_P38_OFFSET            0x180
#define IRQ_P39_OFFSET            0x184
#define IRQ_P40_OFFSET            0x188
#define IRQ_P41_OFFSET            0x18c
#define IRQ_P42_OFFSET            0x190
#define IRQ_P43_OFFSET            0x194
#define IRQ_P44_OFFSET            0x198
#define IRQ_P45_OFFSET            0x19c
#define IRQ_P46_OFFSET            0x1a0
#define IRQ_P47_OFFSET            0x1a4
#define IRQ_P48_OFFSET            0x1a8
#define IRQ_P49_OFFSET            0x1ac
#define IRQ_P50_OFFSET            0x1b0
#define IRQ_P51_OFFSET            0x1b4
#define IRQ_P52_OFFSET            0x1b8
#define IRQ_P53_OFFSET            0x1bc
#define IRQ_P54_OFFSET            0x1c0
#define IRQ_P55_OFFSET            0x1c4
#define IRQ_P56_OFFSET            0x1c8
#define IRQ_P57_OFFSET            0x1cc
#define IRQ_P58_OFFSET            0x1d0
#define IRQ_P59_OFFSET            0x1d4
#define IRQ_P60_OFFSET            0x1d8
#define IRQ_P61_OFFSET            0x1dc
#define IRQ_P62_OFFSET            0x1e0
#define IRQ_P63_OFFSET            0x1e4
#define AHB_ICTL_COMP_PARAMS_2_OFFSET  0x3f0
#define AHB_ICTL_COMP_PARAMS_1_OFFSET  0x3f4
#define AHB_ICTL_COMP_VERSION_OFFSET   0x3f8
#define AHB_ICTL_COMP_TYPE_OFFSET      0x3fc
#define ICTL_VERSION_ID_WIDTH 32


#define ICTL0_IRQ_INTEN          (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_INTEN_OFFSET)))
#define ICTL0_IRQ_INTEN_L        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_INTEN_OFFSET_L)))
#define ICTL0_IRQ_INTEN_H        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_INTEN_OFFSET_H)))
#define ICTL0_IRQ_INTMASK        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_INTMASK_OFFSET)))
#define ICTL0_IRQ_INTMASK_L      (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_INTMASK_OFFSET_L)))
#define ICTL0_IRQ_INTMASK_H      (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_INTMASK_OFFSET_H)))
#define ICTL0_IRQ_INTFORCE       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_INTFORCE_OFFSET)))
#define ICTL0_IRQ_INTFORCE_L     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_INTFORCE_OFFSET_L)))
#define ICTL0_IRQ_INTFORCE_H     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_INTFORCE_OFFSET_H)))
#define ICTL0_IRQ_RAWSTATUS      (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_RAWSTATUS_OFFSET)))
#define ICTL0_IRQ_RAWSTATUS_L    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_RAWSTATUS_OFFSET_L)))
#define ICTL0_IRQ_RAWSTATUS_H    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_RAWSTATUS_OFFSET_H)))
#define ICTL0_IRQ_STATUS         (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_STATUS_OFFSET)))
#define ICTL0_IRQ_STATUS_L       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_STATUS_OFFSET_L)))
#define ICTL0_IRQ_STATUS_H       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_STATUS_OFFSET_H)))
#define ICTL0_IRQ_MASKSTATUS     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_MASKSTATUS_OFFSET)))
#define ICTL0_IRQ_MASKSTATUS_L   (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_MASKSTATUS_OFFSET_L)))
#define ICTL0_IRQ_MASKSTATUS_H   (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_MASKSTATUS_OFFSET_H)))
#define ICTL0_IRQ_FINALSTATUS    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_FINALSTATUS_OFFSET)))
#define ICTL0_IRQ_FINALSTATUS_L  (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_FINALSTATUS_OFFSET_L)))
#define ICTL0_IRQ_FINALSTATUS_H  (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_FINALSTATUS_OFFSET_H)))
#define ICTL0_IRQ_VECTOR         (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET)))
#define ICTL0_IRQ_VECTOR_L       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_L)))
#define ICTL0_IRQ_VECTOR_H       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_H)))
#define ICTL0_IRQ_VECTOR_0       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_0)))
#define ICTL0_IRQ_VECTOR_0_L     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_0_L)))
#define ICTL0_IRQ_VECTOR_0_H     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_0_H)))
#define ICTL0_IRQ_VECTOR_1       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_1)))
#define ICTL0_IRQ_VECTOR_1_L     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_1_L)))
#define ICTL0_IRQ_VECTOR_1_H     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_1_H)))
#define ICTL0_IRQ_VECTOR_2       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_2)))
#define ICTL0_IRQ_VECTOR_2_L     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_2_L)))
#define ICTL0_IRQ_VECTOR_2_H     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_2_H)))
#define ICTL0_IRQ_VECTOR_3       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_3)))
#define ICTL0_IRQ_VECTOR_3_L     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_3_L)))
#define ICTL0_IRQ_VECTOR_3_H     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_3_H)))
#define ICTL0_IRQ_VECTOR_4       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_4)))
#define ICTL0_IRQ_VECTOR_4_L     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_4_L)))
#define ICTL0_IRQ_VECTOR_4_H     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_4_H)))
#define ICTL0_IRQ_VECTOR_5       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_5)))
#define ICTL0_IRQ_VECTOR_5_L     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_5_L)))
#define ICTL0_IRQ_VECTOR_5_H     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_5_H)))
#define ICTL0_IRQ_VECTOR_6       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_6)))
#define ICTL0_IRQ_VECTOR_6_L     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_6_L)))
#define ICTL0_IRQ_VECTOR_6_H     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_6_H)))
#define ICTL0_IRQ_VECTOR_7       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_7)))
#define ICTL0_IRQ_VECTOR_7_L     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_7_L)))
#define ICTL0_IRQ_VECTOR_7_H     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_7_H)))
#define ICTL0_IRQ_VECTOR_8       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_8)))
#define ICTL0_IRQ_VECTOR_8_L     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_8_L)))
#define ICTL0_IRQ_VECTOR_8_H     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_8_H)))
#define ICTL0_IRQ_VECTOR_9       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_9)))
#define ICTL0_IRQ_VECTOR_9_L     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_9_L)))
#define ICTL0_IRQ_VECTOR_9_H     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_9_H)))
#define ICTL0_IRQ_VECTOR_10      (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_10)))
#define ICTL0_IRQ_VECTOR_10_L    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_10_L)))
#define ICTL0_IRQ_VECTOR_10_H    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_10_H)))
#define ICTL0_IRQ_VECTOR_11      (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_11)))
#define ICTL0_IRQ_VECTOR_11_L    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_11_L)))
#define ICTL0_IRQ_VECTOR_11_H    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_11_H)))
#define ICTL0_IRQ_VECTOR_12      (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_12)))
#define ICTL0_IRQ_VECTOR_12_L    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_12_L)))
#define ICTL0_IRQ_VECTOR_12_H    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_12_H)))
#define ICTL0_IRQ_VECTOR_13      (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_13)))
#define ICTL0_IRQ_VECTOR_13_L    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_13_L)))
#define ICTL0_IRQ_VECTOR_13_H    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_13_H)))
#define ICTL0_IRQ_VECTOR_14      (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_14)))
#define ICTL0_IRQ_VECTOR_14_L    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_14_L)))
#define ICTL0_IRQ_VECTOR_14_H    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_14_H)))
#define ICTL0_IRQ_VECTOR_15      (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_15)))
#define ICTL0_IRQ_VECTOR_15_L    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_15_L)))
#define ICTL0_IRQ_VECTOR_15_H    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_VECTOR_OFFSET_15_H)))
#define ICTL0_FIQ_INTEN          (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + FIQ_INTEN_OFFSET)))
#define ICTL0_FIQ_INTMASK        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + FIQ_INTMASK_OFFSET)))
#define ICTL0_FIQ_INTFORCE       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + FIQ_INTFORCE_OFFSET)))
#define ICTL0_FIQ_RAWSTATUS      (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + FIQ_RAWSTATUS_OFFSET)))
#define ICTL0_FIQ_STATUS         (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + FIQ_STATUS_OFFSET)))
#define ICTL0_FIQ_FINALSTATUS    (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + FIQ_FINALSTATUS_OFFSET)))
#define ICTL0_IRQ_PLEVEL         (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_PLEVEL_OFFSET)))
#define ICTL0_IRQ_P0_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P0_OFFSET)))
#define ICTL0_IRQ_P1_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P1_OFFSET)))
#define ICTL0_IRQ_P2_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P2_OFFSET)))
#define ICTL0_IRQ_P3_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P3_OFFSET)))
#define ICTL0_IRQ_P4_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P4_OFFSET)))
#define ICTL0_IRQ_P5_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P5_OFFSET)))
#define ICTL0_IRQ_P6_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P6_OFFSET)))
#define ICTL0_IRQ_P7_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P7_OFFSET)))
#define ICTL0_IRQ_P8_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P8_OFFSET)))
#define ICTL0_IRQ_P9_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P9_OFFSET)))
#define ICTL0_IRQ_P10_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P10_OFFSET)))
#define ICTL0_IRQ_P11_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P11_OFFSET)))
#define ICTL0_IRQ_P12_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P12_OFFSET)))
#define ICTL0_IRQ_P13_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P13_OFFSET)))
#define ICTL0_IRQ_P14_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P14_OFFSET)))
#define ICTL0_IRQ_P15_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P15_OFFSET)))
#define ICTL0_IRQ_P16_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P16_OFFSET)))
#define ICTL0_IRQ_P17_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P17_OFFSET)))
#define ICTL0_IRQ_P18_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P18_OFFSET)))
#define ICTL0_IRQ_P19_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P19_OFFSET)))
#define ICTL0_IRQ_P20_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P20_OFFSET)))
#define ICTL0_IRQ_P21_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P21_OFFSET)))
#define ICTL0_IRQ_P22_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P22_OFFSET)))
#define ICTL0_IRQ_P23_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P23_OFFSET)))
#define ICTL0_IRQ_P24_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P24_OFFSET)))
#define ICTL0_IRQ_P25_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P25_OFFSET)))
#define ICTL0_IRQ_P26_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P26_OFFSET)))
#define ICTL0_IRQ_P27_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P27_OFFSET)))
#define ICTL0_IRQ_P28_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P28_OFFSET)))
#define ICTL0_IRQ_P29_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P29_OFFSET)))
#define ICTL0_IRQ_P29_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P29_OFFSET)))
#define ICTL0_IRQ_P30_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P30_OFFSET)))
#define ICTL0_IRQ_P31_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P31_OFFSET)))
#define ICTL0_IRQ_P32_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P32_OFFSET)))
#define ICTL0_IRQ_P33_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P33_OFFSET)))
#define ICTL0_IRQ_P34_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P34_OFFSET)))
#define ICTL0_IRQ_P35_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P35_OFFSET)))
#define ICTL0_IRQ_P36_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P36_OFFSET)))
#define ICTL0_IRQ_P37_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P37_OFFSET)))
#define ICTL0_IRQ_P38_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P38_OFFSET)))
#define ICTL0_IRQ_P39_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P39_OFFSET)))
#define ICTL0_IRQ_P40_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P40_OFFSET)))
#define ICTL0_IRQ_P41_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P41_OFFSET)))
#define ICTL0_IRQ_P42_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P42_OFFSET)))
#define ICTL0_IRQ_P43_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P43_OFFSET)))
#define ICTL0_IRQ_P44_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P44_OFFSET)))
#define ICTL0_IRQ_P45_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P45_OFFSET)))
#define ICTL0_IRQ_P46_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P46_OFFSET)))
#define ICTL0_IRQ_P47_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P47_OFFSET)))
#define ICTL0_IRQ_P48_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P48_OFFSET)))
#define ICTL0_IRQ_P49_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P49_OFFSET)))
#define ICTL0_IRQ_P50_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P50_OFFSET)))
#define ICTL0_IRQ_P51_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P51_OFFSET)))
#define ICTL0_IRQ_P52_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P52_OFFSET)))
#define ICTL0_IRQ_P53_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P53_OFFSET)))
#define ICTL0_IRQ_P54_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P54_OFFSET)))
#define ICTL0_IRQ_P55_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P55_OFFSET)))
#define ICTL0_IRQ_P56_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P56_OFFSET)))
#define ICTL0_IRQ_P57_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P57_OFFSET)))
#define ICTL0_IRQ_P58_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P58_OFFSET)))
#define ICTL0_IRQ_P59_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P59_OFFSET)))
#define ICTL0_IRQ_P60_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P60_OFFSET)))
#define ICTL0_IRQ_P61_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P61_OFFSET)))
#define ICTL0_IRQ_P62_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P62_OFFSET)))
#define ICTL0_IRQ_P63_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + IRQ_P63_OFFSET)))
#define ICTL0_PING_1BIT_WR       (ICTL0_IRQ_INTEN_L)
#define ICTL0_COMP_PARAMS_2_ADDR (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + AHB_ICTL_COMP_PARAMS_2_OFFSET)))
#define ICTL0_COMP_PARAMS_1_ADDR (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + AHB_ICTL_COMP_PARAMS_1_OFFSET)))
#define ICTL0_COMP_VERSION_ADDR  (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + AHB_ICTL_COMP_VERSION_OFFSET)))
#define ICTL0_COMP_TYPE_ADDR     (*((volatile UINT32 *)(DW_AHB_ICTL0_BASE + AHB_ICTL_COMP_TYPE_OFFSET)))


#define ICTL1_IRQ_INTEN          (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_INTEN_OFFSET)))
#define ICTL1_IRQ_INTEN_L        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_INTEN_OFFSET_L)))
#define ICTL1_IRQ_INTEN_H        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_INTEN_OFFSET_H)))
#define ICTL1_IRQ_INTMASK        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_INTMASK_OFFSET)))
#define ICTL1_IRQ_INTMASK_L      (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_INTMASK_OFFSET_L)))
#define ICTL1_IRQ_INTMASK_H      (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_INTMASK_OFFSET_H)))
#define ICTL1_IRQ_INTFORCE       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_INTFORCE_OFFSET)))
#define ICTL1_IRQ_INTFORCE_L     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_INTFORCE_OFFSET_L)))
#define ICTL1_IRQ_INTFORCE_H     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_INTFORCE_OFFSET_H)))
#define ICTL1_IRQ_RAWSTATUS      (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_RAWSTATUS_OFFSET)))
#define ICTL1_IRQ_RAWSTATUS_L    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_RAWSTATUS_OFFSET_L)))
#define ICTL1_IRQ_RAWSTATUS_H    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_RAWSTATUS_OFFSET_H)))
#define ICTL1_IRQ_STATUS         (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_STATUS_OFFSET)))
#define ICTL1_IRQ_STATUS_L       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_STATUS_OFFSET_L)))
#define ICTL1_IRQ_STATUS_H       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_STATUS_OFFSET_H)))
#define ICTL1_IRQ_MASKSTATUS     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_MASKSTATUS_OFFSET)))
#define ICTL1_IRQ_MASKSTATUS_L   (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_MASKSTATUS_OFFSET_L)))
#define ICTL1_IRQ_MASKSTATUS_H   (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_MASKSTATUS_OFFSET_H)))
#define ICTL1_IRQ_FINALSTATUS    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_FINALSTATUS_OFFSET)))
#define ICTL1_IRQ_FINALSTATUS_L  (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_FINALSTATUS_OFFSET_L)))
#define ICTL1_IRQ_FINALSTATUS_H  (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_FINALSTATUS_OFFSET_H)))
#define ICTL1_IRQ_VECTOR         (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET)))
#define ICTL1_IRQ_VECTOR_L       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_L)))
#define ICTL1_IRQ_VECTOR_H       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_H)))
#define ICTL1_IRQ_VECTOR_0       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_0)))
#define ICTL1_IRQ_VECTOR_0_L     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_0_L)))
#define ICTL1_IRQ_VECTOR_0_H     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_0_H)))
#define ICTL1_IRQ_VECTOR_1       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_1)))
#define ICTL1_IRQ_VECTOR_1_L     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_1_L)))
#define ICTL1_IRQ_VECTOR_1_H     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_1_H)))
#define ICTL1_IRQ_VECTOR_2       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_2)))
#define ICTL1_IRQ_VECTOR_2_L     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_2_L)))
#define ICTL1_IRQ_VECTOR_2_H     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_2_H)))
#define ICTL1_IRQ_VECTOR_3       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_3)))
#define ICTL1_IRQ_VECTOR_3_L     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_3_L)))
#define ICTL1_IRQ_VECTOR_3_H     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_3_H)))
#define ICTL1_IRQ_VECTOR_4       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_4)))
#define ICTL1_IRQ_VECTOR_4_L     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_4_L)))
#define ICTL1_IRQ_VECTOR_4_H     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_4_H)))
#define ICTL1_IRQ_VECTOR_5       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_5)))
#define ICTL1_IRQ_VECTOR_5_L     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_5_L)))
#define ICTL1_IRQ_VECTOR_5_H     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_5_H)))
#define ICTL1_IRQ_VECTOR_6       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_6)))
#define ICTL1_IRQ_VECTOR_6_L     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_6_L)))
#define ICTL1_IRQ_VECTOR_6_H     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_6_H)))
#define ICTL1_IRQ_VECTOR_7       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_7)))
#define ICTL1_IRQ_VECTOR_7_L     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_7_L)))
#define ICTL1_IRQ_VECTOR_7_H     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_7_H)))
#define ICTL1_IRQ_VECTOR_8       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_8)))
#define ICTL1_IRQ_VECTOR_8_L     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_8_L)))
#define ICTL1_IRQ_VECTOR_8_H     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_8_H)))
#define ICTL1_IRQ_VECTOR_9       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_9)))
#define ICTL1_IRQ_VECTOR_9_L     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_9_L)))
#define ICTL1_IRQ_VECTOR_9_H     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_9_H)))
#define ICTL1_IRQ_VECTOR_10      (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_10)))
#define ICTL1_IRQ_VECTOR_10_L    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_10_L)))
#define ICTL1_IRQ_VECTOR_10_H    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_10_H)))
#define ICTL1_IRQ_VECTOR_11      (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_11)))
#define ICTL1_IRQ_VECTOR_11_L    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_11_L)))
#define ICTL1_IRQ_VECTOR_11_H    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_11_H)))
#define ICTL1_IRQ_VECTOR_12      (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_12)))
#define ICTL1_IRQ_VECTOR_12_L    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_12_L)))
#define ICTL1_IRQ_VECTOR_12_H    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_12_H)))
#define ICTL1_IRQ_VECTOR_13      (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_13)))
#define ICTL1_IRQ_VECTOR_13_L    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_13_L)))
#define ICTL1_IRQ_VECTOR_13_H    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_13_H)))
#define ICTL1_IRQ_VECTOR_14      (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_14)))
#define ICTL1_IRQ_VECTOR_14_L    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_14_L)))
#define ICTL1_IRQ_VECTOR_14_H    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_14_H)))
#define ICTL1_IRQ_VECTOR_15      (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_15)))
#define ICTL1_IRQ_VECTOR_15_L    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_15_L)))
#define ICTL1_IRQ_VECTOR_15_H    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_VECTOR_OFFSET_15_H)))
#define ICTL1_FIQ_INTEN          (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + FIQ_INTEN_OFFSET)))
#define ICTL1_FIQ_INTMASK        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + FIQ_INTMASK_OFFSET)))
#define ICTL1_FIQ_INTFORCE       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + FIQ_INTFORCE_OFFSET)))
#define ICTL1_FIQ_RAWSTATUS      (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + FIQ_RAWSTATUS_OFFSET)))
#define ICTL1_FIQ_STATUS         (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + FIQ_STATUS_OFFSET)))
#define ICTL1_FIQ_FINALSTATUS    (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + FIQ_FINALSTATUS_OFFSET)))
#define ICTL1_IRQ_PLEVEL         (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_PLEVEL_OFFSET)))
#define ICTL1_IRQ_P0_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P0_OFFSET)))
#define ICTL1_IRQ_P1_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P1_OFFSET)))
#define ICTL1_IRQ_P2_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P2_OFFSET)))
#define ICTL1_IRQ_P3_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P3_OFFSET)))
#define ICTL1_IRQ_P4_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P4_OFFSET)))
#define ICTL1_IRQ_P5_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P5_OFFSET)))
#define ICTL1_IRQ_P6_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P6_OFFSET)))
#define ICTL1_IRQ_P7_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P7_OFFSET)))
#define ICTL1_IRQ_P8_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P8_OFFSET)))
#define ICTL1_IRQ_P9_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P9_OFFSET)))
#define ICTL1_IRQ_P10_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P10_OFFSET)))
#define ICTL1_IRQ_P11_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P11_OFFSET)))
#define ICTL1_IRQ_P12_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P12_OFFSET)))
#define ICTL1_IRQ_P13_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P13_OFFSET)))
#define ICTL1_IRQ_P14_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P14_OFFSET)))
#define ICTL1_IRQ_P15_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P15_OFFSET)))
#define ICTL1_IRQ_P16_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P16_OFFSET)))
#define ICTL1_IRQ_P17_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P17_OFFSET)))
#define ICTL1_IRQ_P18_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P18_OFFSET)))
#define ICTL1_IRQ_P19_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P19_OFFSET)))
#define ICTL1_IRQ_P20_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P20_OFFSET)))
#define ICTL1_IRQ_P21_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P21_OFFSET)))
#define ICTL1_IRQ_P22_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P22_OFFSET)))
#define ICTL1_IRQ_P23_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P23_OFFSET)))
#define ICTL1_IRQ_P24_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P24_OFFSET)))
#define ICTL1_IRQ_P25_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P25_OFFSET)))
#define ICTL1_IRQ_P26_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P26_OFFSET)))
#define ICTL1_IRQ_P27_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P27_OFFSET)))
#define ICTL1_IRQ_P28_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P28_OFFSET)))
#define ICTL1_IRQ_P29_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P29_OFFSET)))
#define ICTL1_IRQ_P29_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P29_OFFSET)))
#define ICTL1_IRQ_P30_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P30_OFFSET)))
#define ICTL1_IRQ_P31_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P31_OFFSET)))
#define ICTL1_IRQ_P32_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P32_OFFSET)))
#define ICTL1_IRQ_P33_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P33_OFFSET)))
#define ICTL1_IRQ_P34_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P34_OFFSET)))
#define ICTL1_IRQ_P35_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P35_OFFSET)))
#define ICTL1_IRQ_P36_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P36_OFFSET)))
#define ICTL1_IRQ_P37_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P37_OFFSET)))
#define ICTL1_IRQ_P38_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P38_OFFSET)))
#define ICTL1_IRQ_P39_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P39_OFFSET)))
#define ICTL1_IRQ_P40_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P40_OFFSET)))
#define ICTL1_IRQ_P41_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P41_OFFSET)))
#define ICTL1_IRQ_P42_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P42_OFFSET)))
#define ICTL1_IRQ_P43_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P43_OFFSET)))
#define ICTL1_IRQ_P44_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P44_OFFSET)))
#define ICTL1_IRQ_P45_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P45_OFFSET)))
#define ICTL1_IRQ_P46_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P46_OFFSET)))
#define ICTL1_IRQ_P47_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P47_OFFSET)))
#define ICTL1_IRQ_P48_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P48_OFFSET)))
#define ICTL1_IRQ_P49_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P49_OFFSET)))
#define ICTL1_IRQ_P50_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P50_OFFSET)))
#define ICTL1_IRQ_P51_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P51_OFFSET)))
#define ICTL1_IRQ_P52_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P52_OFFSET)))
#define ICTL1_IRQ_P53_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P53_OFFSET)))
#define ICTL1_IRQ_P54_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P54_OFFSET)))
#define ICTL1_IRQ_P55_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P55_OFFSET)))
#define ICTL1_IRQ_P56_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P56_OFFSET)))
#define ICTL1_IRQ_P57_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P57_OFFSET)))
#define ICTL1_IRQ_P58_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P58_OFFSET)))
#define ICTL1_IRQ_P59_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P59_OFFSET)))
#define ICTL1_IRQ_P60_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P60_OFFSET)))
#define ICTL1_IRQ_P61_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P61_OFFSET)))
#define ICTL1_IRQ_P62_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P62_OFFSET)))
#define ICTL1_IRQ_P63_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + IRQ_P63_OFFSET)))
#define ICTL1_PING_1BIT_WR       (ICTL1_IRQ_INTEN_L)
#define ICTL1_COMP_PARAMS_2_ADDR (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + AHB_ICTL_COMP_PARAMS_2_OFFSET)))
#define ICTL1_COMP_PARAMS_1_ADDR (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + AHB_ICTL_COMP_PARAMS_1_OFFSET)))
#define ICTL1_COMP_VERSION_ADDR  (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + AHB_ICTL_COMP_VERSION_OFFSET)))
#define ICTL1_COMP_TYPE_ADDR     (*((volatile UINT32 *)(DW_AHB_ICTL1_BASE + AHB_ICTL_COMP_TYPE_OFFSET)))

#define ICTL2_IRQ_INTEN          (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_INTEN_OFFSET)))
#define ICTL2_IRQ_INTEN_L        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_INTEN_OFFSET_L)))
#define ICTL2_IRQ_INTEN_H        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_INTEN_OFFSET_H)))
#define ICTL2_IRQ_INTMASK        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_INTMASK_OFFSET)))
#define ICTL2_IRQ_INTMASK_L      (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_INTMASK_OFFSET_L)))
#define ICTL2_IRQ_INTMASK_H      (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_INTMASK_OFFSET_H)))
#define ICTL2_IRQ_INTFORCE       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_INTFORCE_OFFSET)))
#define ICTL2_IRQ_INTFORCE_L     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_INTFORCE_OFFSET_L)))
#define ICTL2_IRQ_INTFORCE_H     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_INTFORCE_OFFSET_H)))
#define ICTL2_IRQ_RAWSTATUS      (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_RAWSTATUS_OFFSET)))
#define ICTL2_IRQ_RAWSTATUS_L    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_RAWSTATUS_OFFSET_L)))
#define ICTL2_IRQ_RAWSTATUS_H    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_RAWSTATUS_OFFSET_H)))
#define ICTL2_IRQ_STATUS         (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_STATUS_OFFSET)))
#define ICTL2_IRQ_STATUS_L       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_STATUS_OFFSET_L)))
#define ICTL2_IRQ_STATUS_H       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_STATUS_OFFSET_H)))
#define ICTL2_IRQ_MASKSTATUS     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_MASKSTATUS_OFFSET)))
#define ICTL2_IRQ_MASKSTATUS_L   (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_MASKSTATUS_OFFSET_L)))
#define ICTL2_IRQ_MASKSTATUS_H   (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_MASKSTATUS_OFFSET_H)))
#define ICTL2_IRQ_FINALSTATUS    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_FINALSTATUS_OFFSET)))
#define ICTL2_IRQ_FINALSTATUS_L  (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_FINALSTATUS_OFFSET_L)))
#define ICTL2_IRQ_FINALSTATUS_H  (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_FINALSTATUS_OFFSET_H)))
#define ICTL2_IRQ_VECTOR         (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET)))
#define ICTL2_IRQ_VECTOR_L       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_L)))
#define ICTL2_IRQ_VECTOR_H       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_H)))
#define ICTL2_IRQ_VECTOR_0       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_0)))
#define ICTL2_IRQ_VECTOR_0_L     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_0_L)))
#define ICTL2_IRQ_VECTOR_0_H     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_0_H)))
#define ICTL2_IRQ_VECTOR_1       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_1)))
#define ICTL2_IRQ_VECTOR_1_L     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_1_L)))
#define ICTL2_IRQ_VECTOR_1_H     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_1_H)))
#define ICTL2_IRQ_VECTOR_2       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_2)))
#define ICTL2_IRQ_VECTOR_2_L     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_2_L)))
#define ICTL2_IRQ_VECTOR_2_H     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_2_H)))
#define ICTL2_IRQ_VECTOR_3       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_3)))
#define ICTL2_IRQ_VECTOR_3_L     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_3_L)))
#define ICTL2_IRQ_VECTOR_3_H     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_3_H)))
#define ICTL2_IRQ_VECTOR_4       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_4)))
#define ICTL2_IRQ_VECTOR_4_L     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_4_L)))
#define ICTL2_IRQ_VECTOR_4_H     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_4_H)))
#define ICTL2_IRQ_VECTOR_5       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_5)))
#define ICTL2_IRQ_VECTOR_5_L     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_5_L)))
#define ICTL2_IRQ_VECTOR_5_H     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_5_H)))
#define ICTL2_IRQ_VECTOR_6       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_6)))
#define ICTL2_IRQ_VECTOR_6_L     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_6_L)))
#define ICTL2_IRQ_VECTOR_6_H     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_6_H)))
#define ICTL2_IRQ_VECTOR_7       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_7)))
#define ICTL2_IRQ_VECTOR_7_L     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_7_L)))
#define ICTL2_IRQ_VECTOR_7_H     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_7_H)))
#define ICTL2_IRQ_VECTOR_8       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_8)))
#define ICTL2_IRQ_VECTOR_8_L     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_8_L)))
#define ICTL2_IRQ_VECTOR_8_H     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_8_H)))
#define ICTL2_IRQ_VECTOR_9       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_9)))
#define ICTL2_IRQ_VECTOR_9_L     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_9_L)))
#define ICTL2_IRQ_VECTOR_9_H     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_9_H)))
#define ICTL2_IRQ_VECTOR_10      (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_10)))
#define ICTL2_IRQ_VECTOR_10_L    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_10_L)))
#define ICTL2_IRQ_VECTOR_10_H    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_10_H)))
#define ICTL2_IRQ_VECTOR_11      (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_11)))
#define ICTL2_IRQ_VECTOR_11_L    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_11_L)))
#define ICTL2_IRQ_VECTOR_11_H    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_11_H)))
#define ICTL2_IRQ_VECTOR_12      (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_12)))
#define ICTL2_IRQ_VECTOR_12_L    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_12_L)))
#define ICTL2_IRQ_VECTOR_12_H    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_12_H)))
#define ICTL2_IRQ_VECTOR_13      (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_13)))
#define ICTL2_IRQ_VECTOR_13_L    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_13_L)))
#define ICTL2_IRQ_VECTOR_13_H    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_13_H)))
#define ICTL2_IRQ_VECTOR_14      (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_14)))
#define ICTL2_IRQ_VECTOR_14_L    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_14_L)))
#define ICTL2_IRQ_VECTOR_14_H    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_14_H)))
#define ICTL2_IRQ_VECTOR_15      (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_15)))
#define ICTL2_IRQ_VECTOR_15_L    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_15_L)))
#define ICTL2_IRQ_VECTOR_15_H    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_VECTOR_OFFSET_15_H)))
#define ICTL2_FIQ_INTEN          (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + FIQ_INTEN_OFFSET)))
#define ICTL2_FIQ_INTMASK        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + FIQ_INTMASK_OFFSET)))
#define ICTL2_FIQ_INTFORCE       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + FIQ_INTFORCE_OFFSET)))
#define ICTL2_FIQ_RAWSTATUS      (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + FIQ_RAWSTATUS_OFFSET)))
#define ICTL2_FIQ_STATUS         (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + FIQ_STATUS_OFFSET)))
#define ICTL2_FIQ_FINALSTATUS    (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + FIQ_FINALSTATUS_OFFSET)))
#define ICTL2_IRQ_PLEVEL         (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_PLEVEL_OFFSET)))
#define ICTL2_IRQ_P0_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P0_OFFSET)))
#define ICTL2_IRQ_P1_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P1_OFFSET)))
#define ICTL2_IRQ_P2_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P2_OFFSET)))
#define ICTL2_IRQ_P3_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P3_OFFSET)))
#define ICTL2_IRQ_P4_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P4_OFFSET)))
#define ICTL2_IRQ_P5_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P5_OFFSET)))
#define ICTL2_IRQ_P6_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P6_OFFSET)))
#define ICTL2_IRQ_P7_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P7_OFFSET)))
#define ICTL2_IRQ_P8_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P8_OFFSET)))
#define ICTL2_IRQ_P9_ADDR        (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P9_OFFSET)))
#define ICTL2_IRQ_P10_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P10_OFFSET)))
#define ICTL2_IRQ_P11_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P11_OFFSET)))
#define ICTL2_IRQ_P12_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P12_OFFSET)))
#define ICTL2_IRQ_P13_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P13_OFFSET)))
#define ICTL2_IRQ_P14_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P14_OFFSET)))
#define ICTL2_IRQ_P15_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P15_OFFSET)))
#define ICTL2_IRQ_P16_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P16_OFFSET)))
#define ICTL2_IRQ_P17_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P17_OFFSET)))
#define ICTL2_IRQ_P18_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P18_OFFSET)))
#define ICTL2_IRQ_P19_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P19_OFFSET)))
#define ICTL2_IRQ_P20_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P20_OFFSET)))
#define ICTL2_IRQ_P21_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P21_OFFSET)))
#define ICTL2_IRQ_P22_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P22_OFFSET)))
#define ICTL2_IRQ_P23_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P23_OFFSET)))
#define ICTL2_IRQ_P24_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P24_OFFSET)))
#define ICTL2_IRQ_P25_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P25_OFFSET)))
#define ICTL2_IRQ_P26_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P26_OFFSET)))
#define ICTL2_IRQ_P27_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P27_OFFSET)))
#define ICTL2_IRQ_P28_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P28_OFFSET)))
#define ICTL2_IRQ_P29_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P29_OFFSET)))
#define ICTL2_IRQ_P29_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P29_OFFSET)))
#define ICTL2_IRQ_P30_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P30_OFFSET)))
#define ICTL2_IRQ_P31_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P31_OFFSET)))
#define ICTL2_IRQ_P32_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P32_OFFSET)))
#define ICTL2_IRQ_P33_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P33_OFFSET)))
#define ICTL2_IRQ_P34_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P34_OFFSET)))
#define ICTL2_IRQ_P35_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P35_OFFSET)))
#define ICTL2_IRQ_P36_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P36_OFFSET)))
#define ICTL2_IRQ_P37_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P37_OFFSET)))
#define ICTL2_IRQ_P38_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P38_OFFSET)))
#define ICTL2_IRQ_P39_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P39_OFFSET)))
#define ICTL2_IRQ_P40_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P40_OFFSET)))
#define ICTL2_IRQ_P41_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P41_OFFSET)))
#define ICTL2_IRQ_P42_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P42_OFFSET)))
#define ICTL2_IRQ_P43_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P43_OFFSET)))
#define ICTL2_IRQ_P44_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P44_OFFSET)))
#define ICTL2_IRQ_P45_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P45_OFFSET)))
#define ICTL2_IRQ_P46_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P46_OFFSET)))
#define ICTL2_IRQ_P47_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P47_OFFSET)))
#define ICTL2_IRQ_P48_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P48_OFFSET)))
#define ICTL2_IRQ_P49_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P49_OFFSET)))
#define ICTL2_IRQ_P50_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P50_OFFSET)))
#define ICTL2_IRQ_P51_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P51_OFFSET)))
#define ICTL2_IRQ_P52_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P52_OFFSET)))
#define ICTL2_IRQ_P53_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P53_OFFSET)))
#define ICTL2_IRQ_P54_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P54_OFFSET)))
#define ICTL2_IRQ_P55_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P55_OFFSET)))
#define ICTL2_IRQ_P56_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P56_OFFSET)))
#define ICTL2_IRQ_P57_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P57_OFFSET)))
#define ICTL2_IRQ_P58_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P58_OFFSET)))
#define ICTL2_IRQ_P59_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P59_OFFSET)))
#define ICTL2_IRQ_P60_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P60_OFFSET)))
#define ICTL2_IRQ_P61_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P61_OFFSET)))
#define ICTL2_IRQ_P62_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P62_OFFSET)))
#define ICTL2_IRQ_P63_ADDR       (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + IRQ_P63_OFFSET)))
#define ICTL2_PING_1BIT_WR       (ICTL2_IRQ_INTEN_L)
#define ICTL2_COMP_PARAMS_2_ADDR (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + AHB_ICTL_COMP_PARAMS_2_OFFSET)))
#define ICTL2_COMP_PARAMS_1_ADDR (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + AHB_ICTL_COMP_PARAMS_1_OFFSET)))
#define ICTL2_COMP_VERSION_ADDR  (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + AHB_ICTL_COMP_VERSION_OFFSET)))
#define ICTL2_COMP_TYPE_ADDR     (*((volatile UINT32 *)(DW_AHB_ICTL2_BASE + AHB_ICTL_COMP_TYPE_OFFSET)))

#endif
